[package]
authors = ["ai-coustics GmbH"]
description = "Node.js Bindings for ai-coustics SDK"
edition = "2024"
exclude = ["index.node"]
license = "Apache-2.0"
name = "aic-sdk-node"
rust-version = "1.87"
version = "0.22.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
aic-sdk = { git = "https://github.com/ai-coustics/aic-sdk-rs", rev = "fd3e596b3e2dafe01a985d4edd1b720862dd8c94", features = ["download-lib", "download-model"] }
neon = "1.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
