/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Analyzer for analysis models such as Tyto.
 *
 * Buffering and analysis are deliberately separate calls: {@link Analyzer#buffer} is cheap
 * enough for the audio path, while running the model is not. Analysis therefore comes in
 * two forms: {@link Analyzer#analyzeAsync} on a worker thread, and
 * {@link Analyzer#analyze} on the calling thread.
 *
 * Only a fixed span of audio is retained, determined by the model; older audio is
 * discarded as more is buffered.
 *
 * The SDK splits this into a collector and an analyzer so the two halves can live on
 * different threads. A class instance cannot cross into a Node worker, so both are exposed
 * as one object here, but the split still shows through: {@link Analyzer#buffer} drives
 * the collector on the calling thread, while {@link Analyzer#analyzeAsync} moves the
 * analyzer half onto a worker. The SDK guarantees the two are safe to use concurrently.
 */
export declare class Analyzer {
  /** Creates an analyzer from an analysis model. Other model types are rejected. */
  constructor(model: Model, licenseKey: string)
  /**
   * Destroys the native collector and analyzer immediately, releasing their memory
   * without waiting for garbage collection.
   *
   * Every later method throws; calling `dispose()` again does nothing. Blocks until an
   * in-flight `analyzeAsync` on a worker thread finishes.
   */
  dispose(): void
  /**
   * Configures the analyzer for an audio format. Must be called before buffering.
   *
   * The model's optimal sample rate and block size avoid internal resampling and
   * rebuffering. Allocates, so keep it off the audio path.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): void
  /** Buffers a mono audio block for later analysis, leaving the audio unmodified. */
  buffer(audio: Float32Array): void
  /**
   * Runs the analysis model over the buffered audio, on the calling thread.
   *
   * The model consumes a fixed span of audio. Calling this before that much has been
   * buffered analyzes what is there, padded with silence.
   *
   * Analysis is mono. Mix multichannel audio down, or use one analyzer per channel.
   *
   * This is the expensive call, and it blocks. Prefer {@link Analyzer#analyzeAsync} unless
   * nothing else is waiting on the event loop.
   */
  analyze(): AnalysisResult
  /**
   * Runs the analysis model over the buffered audio on a worker thread.
   *
   * Same result as {@link Analyzer#analyze}, off the event loop. The SDK's
   * analysis models are too expensive to run on an audio thread, so this is the form to
   * reach for in a server: analysis is occasional, and a promise costs nothing next to
   * the model.
   *
   * {@link Analyzer#buffer} stays synchronous and takes no lock, so audio can keep arriving
   * while an analysis is in flight. The SDK guarantees the collector and analyzer halves
   * are safe to use concurrently. The other methods here do take the analyzer's lock, so
   * calling {@link Analyzer#analyze}, {@link Analyzer#reset} or
   * {@link Analyzer#terminateSession} while this is pending blocks the calling thread until
   * it finishes.
   */
  analyzeAsync(): Promise<AnalysisResult>
  /** Clears buffered audio and internal state, keeping the configured audio settings. */
  reset(): void
  /**
   * Swaps in a renewed JWT without tearing down the analyzer.
   *
   * Only works when both the original key and the new token are JWTs. On failure the
   * call is a no-op and the previous token stays active.
   */
  updateBearerToken(token: string): void
  /** Ends this analyzer's telemetry session, after which it can no longer analyze audio. */
  terminateSession(): void
}

/**
 * A loaded ai-coustics model.
 *
 * One model can back multiple processors, VADs and analyzers, according to its type.
 * The underlying model data is kept alive by every object created from it through
 * internal reference counting, so this handle may be released first.
 */
export declare class Model {
  /**
   * Loads a model from a `.aicmodel` file.
   *
   * The model data is memory-mapped, not copied into the process, so the file must
   * not be modified or deleted while this model, or any object created from it,
   * is alive.
   *
   * Browse available models at <https://artifacts.ai-coustics.io>, or fetch one with
   * {@link Model.download}.
   */
  static fromFile(path: string): Model
  /**
   * Unmaps the model file immediately, releasing its footprint without waiting for
   * garbage collection.
   *
   * Objects already created from the model keep working: the SDK keeps the weights
   * alive through internal reference counting. Every later method on this handle
   * throws; calling `dispose()` again does nothing.
   */
  dispose(): void
  /**
   * Downloads a model from the ai-coustics artifact CDN and resolves to its path.
   *
   * The manifest is re-fetched on every call so the newest compatible model version
   * is always used. An existing file with a matching checksum is not re-downloaded;
   * one with a mismatching checksum is replaced.
   *
   * The download runs on a worker thread, so it does not block the event loop.
   */
  static download(modelId: string, downloadDir: string): Promise<string>
  /** The model identifier, e.g. `quail-vf-2.2-s-16khz`. */
  getId(): string
  /**
   * The sample rate in Hz the model was trained for.
   *
   * Audio at any rate can be processed, but a model only enhances frequencies up to
   * its own Nyquist limit, so matching this rate gives the best quality.
   */
  getOptimalSampleRate(): number
  /**
   * The block size that avoids internal buffering at `sampleRate`.
   *
   * Any other block size adds buffering latency on top of the base processing delay.
   * The value changes with the sample rate, because the model works on a fixed time
   * window: a 10 ms window is 480 samples at 48 kHz but 160 at 16 kHz.
   */
  getOptimalBlockSize(sampleRate: number): number
}

/**
 * Speech enhancement processor.
 *
 * Built from an enhancement or bypass model. Use {@link Vad} for dedicated VAD models
 * and {@link Analyzer} for analysis models; passing the wrong kind throws.
 *
 * Create several processors to handle multiple streams or to switch models at runtime.
 */
export declare class Processor {
  /**
   * Creates a processor from an enhancement or bypass model.
   *
   * Telemetry follows the runtime environment; pass `otelConfig` to override it for this
   * instance.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native processor immediately, releasing its memory and telemetry
   * session without waiting for garbage collection.
   *
   * Every later method throws; calling `dispose()` again does nothing.
   */
  dispose(): void
  /**
   * Configures the processor for an audio format. Must be called before processing.
   *
   * For the lowest delay use {@link Model#getOptimalSampleRate} and
   * {@link Model#getOptimalBlockSize}. Allocates, so keep it off the audio path.
   *
   * With `variableBlockSize` enabled (default `false`), calls shorter than `blockSize`
   * are permitted at the cost of extra delay; longer calls are always rejected.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): void
  /**
   * Enhances a mono audio block in place.
   *
   * The block must be exactly `blockSize` samples, or at most `blockSize` if
   * `variableBlockSize` was enabled.
   */
  process(audio: Float32Array): void
  /**
   * Creates a handle for reading and writing this processor's parameters and state.
   *
   * Each call returns an independent handle onto the same processor.
   */
  getContext(): ProcessorContext
  /**
   * Ends this processor's telemetry session, after which it can no longer process audio.
   *
   * Intended for lifecycle events: a session is closed automatically when the processor
   * is collected, but GC timing is not guaranteed. May block, so keep it off the audio path.
   */
  terminateSession(): void
}

/**
 * Speech enhancement processor that keeps its work off the main thread.
 *
 * The same processing as {@link Processor}, but each call returns a promise and runs on
 * Node's libuv thread pool, so the event loop stays responsive. Prefer this when other
 * work shares that loop, as in a server; prefer {@link Processor} on a dedicated audio
 * thread or in a batch script, where nothing else needs the loop.
 *
 * Mirrors `ProcessorAsync` in the Rust SDK.
 *
 * ### Concurrency
 *
 * One instance handles one stream. Do not start a second {@link ProcessorAsync#process}
 * before the first resolves: libuv completes work items out of order, which would
 * desync the stream. To process several streams at once, create several instances.
 *
 * The libuv pool is four threads by default and is shared with `fs`, `dns` and `crypto`.
 * Raise `UV_THREADPOOL_SIZE` before Node starts to run more streams in parallel. The
 * SDK's own `AIC_NUM_THREADS` does not apply here: that variable sizes a rayon pool this
 * binding deliberately does not use.
 */
export declare class ProcessorAsync {
  /**
   * Creates a processor from an enhancement or bypass model.
   *
   * Construction is synchronous and throws on failure, as in the Rust SDK; only the
   * audio work is deferred to a worker thread.
   *
   * Telemetry follows the runtime environment; pass `otelConfig` to override it for this
   * instance.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native processor immediately, releasing its memory and telemetry
   * session without waiting for garbage collection.
   *
   * Every later method throws; calling `dispose()` again does nothing. The synchronous
   * variant blocks until in-flight work on the libuv pool finishes.
   */
  dispose(): void
  /**
   * Initializes the processor and resolves to a handle onto it, for chaining off the
   * constructor:
   *
   * ```js
   * const processor = await new ProcessorAsync(model, licenseKey).withConfig(48000, 480)
   * ```
   *
   * The handle it resolves to drives the same underlying processor as the receiver, so
   * either one can be used afterwards. Rust returns `self` here, which JS cannot express.
   */
  withConfig(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<ProcessorAsync>
  /**
   * Configures the processor for an audio format. Must be called before processing.
   *
   * See {@link Processor#initialize}. Allocates, which is why it runs on a worker.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<void>
  /**
   * Enhances a mono audio block and resolves to the enhanced samples.
   *
   * Unlike {@link Processor#process} this does **not** write into the caller's array.
   * The samples are copied out before the work is queued, so the input stays valid and
   * untouched no matter what the caller does while the promise is pending, and the
   * result arrives as a new array:
   *
   * ```js
   * let audio = new Float32Array(blockSize)
   * for (;;) audio = await processor.process(audio)
   * ```
   *
   * The block must be exactly `blockSize` samples, or at most `blockSize` if
   * `variableBlockSize` was enabled.
   */
  process(audio: Float32Array): Promise<Float32Array<ArrayBuffer>>
  /**
   * Creates a handle for reading and writing this processor's parameters and state.
   *
   * Asynchronous because it takes the processor lock, which a queued `process` may
   * briefly hold; awaiting keeps that wait off the event loop. The returned handle is
   * the same {@link ProcessorContext} the synchronous class hands out, and every one of
   * its methods is synchronous.
   */
  getContext(): Promise<ProcessorContext>
  /**
   * Ends this processor's telemetry session, after which it can no longer process audio.
   *
   * May block, which is why it runs on a worker.
   */
  terminateSession(): Promise<void>
}

/**
 * Control handle for a {@link Processor}.
 *
 * Every method may be called while audio is being processed. Releasing the handle does
 * not destroy the processor it came from.
 */
export declare class ProcessorContext {
  /** Sets an enhancement parameter. Throws if the value is out of range. */
  setParameter(parameter: ProcessorParameter, value: number): void
  /** Reads the current value of a parameter. */
  getParameter(parameter: ProcessorParameter): number
  /**
   * Total delay the processor applies to the audio, in samples at the initialized rate.
   *
   * Covers algorithmic delay plus any buffering from a non-optimal block size. Before
   * initialization it reports the base delay at the model's optimal settings.
   */
  getAudioDelay(): number
  /**
   * Clears internal state and buffers, keeping the configured audio settings.
   *
   * Call this on a stream discontinuity or when seeking, to keep earlier audio from
   * bleeding into the output.
   */
  reset(): void
  /**
   * Swaps in a renewed JWT without interrupting processing.
   *
   * Only works when both the original key and the new token are JWTs. On failure the
   * call is a no-op and the previous token stays active. On success the swap is applied
   * immediately and is not gated on backend acceptance.
   */
  updateBearerToken(token: string): void
}

/**
 * Voice activity detector running a dedicated VAD model.
 *
 * Driven explicitly through {@link Vad#process} and independent of any
 * {@link Processor}; predictions are read through a {@link VadContext}. Enhancement
 * models are rejected.
 *
 * When enhancement and detection run together, feed this the **original** audio, not the
 * processor's output: enhancement changes the signal the VAD model expects, and stacks
 * the processor's delay onto the prediction. Since `process` leaves its input untouched,
 * calling it on the same block before `Processor#process` is enough.
 */
export declare class Vad {
  /**
   * Creates a voice activity detector from a dedicated VAD model.
   *
   * Telemetry follows the runtime environment; pass `otelConfig` to override it for this
   * instance.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native VAD immediately, releasing its memory and telemetry session
   * without waiting for garbage collection.
   *
   * Every later method throws; calling `dispose()` again does nothing.
   */
  dispose(): void
  /**
   * Configures the VAD for an audio format. Must be called before processing.
   *
   * The model's optimal sample rate and block size give the most frequent prediction
   * updates. Allocates, so keep it off the audio path.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): void
  /** Examines a mono audio block and updates the prediction, leaving the audio unmodified. */
  process(audio: Float32Array): void
  /**
   * Creates a handle for reading predictions and controlling this VAD.
   *
   * Each call returns an independent handle onto the same VAD.
   */
  getContext(): VadContext
  /** Ends this VAD's telemetry session, after which it can no longer process audio. */
  terminateSession(): void
}

/**
 * Voice activity detector that keeps its work off the main thread.
 *
 * The same detection as {@link Vad}, but each call returns a promise and runs on Node's
 * libuv thread pool, so the event loop stays responsive. Predictions are read through a
 * {@link VadContext}, whose methods are all synchronous.
 *
 * Mirrors `VadAsync` in the Rust SDK.
 *
 * As with {@link Vad}, feed this the **original** audio when enhancement and detection
 * run together, not a processor's output.
 *
 * ### Concurrency
 *
 * One instance handles one stream. Do not start a second {@link VadAsync#process} before
 * the first resolves: libuv completes work items out of order, which would desync the
 * stream and scramble the prediction. To watch several streams at once, create several
 * instances.
 *
 * The libuv pool is four threads by default and is shared with `fs`, `dns` and `crypto`.
 * Raise `UV_THREADPOOL_SIZE` before Node starts to run more streams in parallel. The
 * SDK's own `AIC_NUM_THREADS` does not apply here: that variable sizes a rayon pool this
 * binding deliberately does not use.
 */
export declare class VadAsync {
  /**
   * Creates a voice activity detector from a dedicated VAD model.
   *
   * Construction is synchronous and throws on failure, as in the Rust SDK; only the
   * audio work is deferred to a worker thread.
   *
   * Telemetry follows the runtime environment; pass `otelConfig` to override it for this
   * instance.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native VAD immediately, releasing its memory and telemetry session
   * without waiting for garbage collection.
   *
   * Every later method throws; calling `dispose()` again does nothing. The synchronous
   * variant blocks until in-flight work on the libuv pool finishes.
   */
  dispose(): void
  /**
   * Initializes the VAD and resolves to a handle onto it, for chaining off the
   * constructor:
   *
   * ```js
   * const vad = await new VadAsync(model, licenseKey).withConfig(16000, 160)
   * ```
   *
   * The handle it resolves to drives the same underlying VAD as the receiver, so either
   * one can be used afterwards. Rust returns `self` here, which JS cannot express.
   */
  withConfig(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<VadAsync>
  /**
   * Configures the VAD for an audio format. Must be called before processing.
   *
   * See {@link Vad#initialize}. Allocates, which is why it runs on a worker.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<void>
  /**
   * Examines a mono audio block, updates the prediction, and resolves to the same
   * samples unmodified.
   *
   * The samples are copied out before the work is queued, so the caller's array stays
   * valid and untouched no matter what it does while the promise is pending. The block
   * is handed back (rather than resolving to nothing) to match the Rust SDK, so a
   * streaming loop reads the same either side of the boundary:
   *
   * ```js
   * let audio = new Float32Array(blockSize)
   * for (;;) {
   *   audio = await vad.process(audio)
   *   console.log(context.isSpeechDetected())
   * }
   * ```
   */
  process(audio: Float32Array): Promise<Float32Array<ArrayBuffer>>
  /**
   * Creates a handle for reading predictions and controlling this VAD.
   *
   * Asynchronous because it takes the VAD lock, which a queued `process` may briefly
   * hold; awaiting keeps that wait off the event loop. The returned handle is the same
   * {@link VadContext} the synchronous class hands out, and every one of its methods is
   * synchronous, so a prediction can be read from inside an audio callback.
   */
  getContext(): Promise<VadContext>
  /**
   * Ends this VAD's telemetry session, after which it can no longer process audio.
   *
   * May block, which is why it runs on a worker.
   */
  terminateSession(): Promise<void>
}

/**
 * Control handle for a {@link Vad}.
 *
 * Every method may be called while audio is being processed. If the backing VAD is
 * released the prediction stops updating, but this handle stays valid.
 */
export declare class VadContext {
  /** Sets a VAD parameter. Throws if the value is out of range. */
  setParameter(parameter: VadParameter, value: number): void
  /** Reads the current value of a VAD parameter. */
  getParameter(parameter: VadParameter): number
  /**
   * Whether speech is currently detected.
   *
   * The decision lags its input by {@link VadContext#getPredictionDelay} samples, and
   * stops updating if the backing VAD stops being processed.
   */
  isSpeechDetected(): boolean
  /**
   * The model's raw prediction, in the range 0.0 - 1.0.
   *
   * Unlike {@link VadContext#isSpeechDetected} this skips the SDK's post-processing
   * (speech hold, sensitivity thresholding), which is useful for building your own
   * abstractions on top. The same latency notes apply.
   */
  getRawVadProbability(): number
  /**
   * How far the prediction lags its input, in samples at the initialized rate.
   *
   * Covers input reblocking, STFT and model processing. This delay is **not** applied to
   * the audio (`process` leaves the buffer untouched), so use it to line speech
   * decisions up with the audio timeline. Independent of a processor's audio delay.
   */
  getPredictionDelay(): number
  /**
   * Clears internal state, including the published prediction.
   *
   * Call this on a stream discontinuity or when seeking, to keep earlier audio from
   * causing mispredictions.
   */
  reset(): void
  /**
   * Swaps in a renewed JWT without interrupting processing.
   *
   * Only works when both the original key and the new token are JWTs. On failure the
   * call is a no-op and the previous token stays active.
   */
  updateBearerToken(token: string): void
}

/**
 * Overrides the telemetry wrapper id. Internal only, for ai-coustics wrappers embedding
 * this package (e.g. the LiveKit plugin): call before constructing any `Processor`, `Vad`
 * or `Analyzer`, whose constructors otherwise claim the id for this SDK. The id can only
 * be set once per process; later writes are silently discarded.
 */
export declare function _setSdkId(id: number): void

/**
 * Scores produced by {@link Analyzer#analyze}.
 *
 * Every score runs 0.0 - 1.0. For all of them except `speakerLoudness`, lower means less
 * problematic audio.
 */
export interface AnalysisResult {
  /**
   * Headline score: how likely this audio is to break downstream models such as
   * speech-to-text, VAD, turn-taking or speech-to-speech.
   */
  riskScore: number
  /** How distant and reverberant the speaker sounds. */
  speakerReverb: number
  /** How loud the speaker is. */
  speakerLoudness: number
  /** How much speech from people other than the main speaker is present. */
  interferingSpeech: number
  /** How much ambient or environmental noise is present. */
  noise: number
  /** Artifacts from lossy speech codecs, e.g. a low bitrate or narrowband codec. */
  codecDegradation: number
  /**
   * Dropouts and discontinuities, e.g. from packet loss, frame erasure, jitter or CPU
   * overload.
   */
  packetLoss: number
}

/**
 * The model file format version this SDK can load.
 *
 * Model URLs are versioned by this number, so it decides which model files are usable.
 */
export declare function getCompatibleModelVersion(): number

/**
 * The version of the underlying native SDK, e.g. `"0.23.0"`.
 *
 * Not necessarily this package's version.
 */
export declare function getVersion(): string

/**
 * Per-instance OpenTelemetry settings.
 *
 * Overrides the environment-based defaults (e.g. `AIC_SDK_OTEL_ENABLE`) for the one
 * processor or VAD it is passed to.
 */
export interface OtelConfig {
  /** Whether to export telemetry. */
  enable: boolean
  /** Session id to report. A random one is generated when omitted. */
  sessionId?: string
  /** Metric export interval in milliseconds. Omit or pass 0 for the SDK default of 60000. */
  exportIntervalMs?: number
}

/** Enhancement parameters, all changeable while audio is being processed. */
export declare const enum ProcessorParameter {
  /**
   * Bypasses processing while preserving the algorithmic delay, so enhancement can be
   * toggled without clicks or timing shifts.
   *
   * Range 0.0 - 1.0, where 0.0 is enhancement active and 1.0 is latency-compensated
   * passthrough. Defaults to 0.0.
   */
  Bypass = 0,
  /**
   * Tunes enhancement strength for a given STT engine, environment or UX requirement.
   *
   * Quail models suppress noise more aggressively as this rises (and, with Voice Focus,
   * competing speech too); Rook models change the mixback. Range 0.0 - 1.0.
   */
  EnhancementLevel = 1
}

/** Voice activity detection parameters, all changeable while audio is being processed. */
export declare const enum VadParameter {
  /**
   * How long the VAD keeps reporting speech after speech stops, which stabilizes
   * detected -> not-detected transitions.
   *
   * Speech is reported when at least half the blocks in the last
   * `speechHoldDuration * 2` seconds contained speech, so ongoing speech extends the
   * hold. Rounded to the model's window length, so reads may differ from writes.
   *
   * Range 0.0 to 300x the model window length, in seconds. Model-specific default.
   */
  SpeechHoldDuration = 0,
  /**
   * Probability threshold above which a block counts as speech, stabilizing how
   * readily speech is detected at all.
   *
   * Range 0.0 - 1.0. Model-specific default.
   */
  Sensitivity = 1,
  /**
   * How long speech must be present before the VAD reports it, which stabilizes
   * not-detected -> detected transitions.
   *
   * Rounded to the model's window length, so reads may differ from writes.
   * Range 0.0 - 1.0, in seconds. Model-specific default.
   */
  MinimumSpeechDuration = 2
}
