/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Analyzes audio quality using an analysis model, such as Tyto.
 *
 * Call {@link Analyzer#initialize}, then {@link Analyzer#buffer} to collect mono audio.
 * The model determines how much audio is retained; older samples are discarded as new
 * audio arrives.
 *
 * Run {@link Analyzer#analyzeAsync} to analyze the buffered audio on a libuv worker
 * thread, or {@link Analyzer#analyze} to run it on the calling thread. Analysis is
 * computationally expensive and should not run in audio processing callbacks.
 * Buffering remains synchronous and can continue while async analysis is running.
 */
export declare class Analyzer {
  /**
   * Creates an analyzer from an analysis model.
   *
   * Construction allocates memory. Call {@link Analyzer#initialize} before buffering audio.
   *
   * @param model - Analysis model. Other model types are rejected.
   * @param licenseKey - SDK license key from https://developers.ai-coustics.com.
   */
  constructor(model: Model, licenseKey: string)
  /**
   * Destroys the native collector and analyzer without waiting for garbage collection.
   *
   * After disposal, all methods except `dispose()` fail. Repeated disposal has no effect.
   * This call blocks the calling thread while a worker holds the analyzer lock.
   * Queued analysis that acquires the lock after disposal rejects its promise.
   */
  dispose(): void
  /**
   * Configures the analyzer's audio collector.
   *
   * Call this before buffering audio. Use {@link Model#getOptimalSampleRate} and
   * {@link Model#getOptimalBlockSize} to avoid internal resampling and rebuffering.
   * This method allocates memory; avoid calling it from audio processing callbacks.
   *
   * @param sampleRate - Audio sample rate in Hz.
   * @param blockSize - Number of mono samples per block.
   * @param variableBlockSize - Allow blocks shorter than `blockSize`. Defaults to `false`.
   *   Blocks larger than `blockSize` are always rejected.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): void
  /**
   * Buffers a mono audio block for later analysis without modifying the input.
   *
   * Call {@link Analyzer#initialize} first. The block must contain exactly `blockSize`
   * samples, or at most `blockSize` if `variableBlockSize` is enabled.
   * Buffering does not acquire the analyzer lock and can run during async analysis.
   */
  buffer(audio: Float32Array): void
  /**
   * Analyzes buffered audio on the calling thread and returns the scores.
   *
   * The model analyzes a fixed duration of audio. If less audio has been buffered, the
   * remaining input is padded with silence.
   *
   * This method blocks the calling thread. Use {@link Analyzer#analyzeAsync} to keep the
   * event loop available. For multichannel audio, mix down to mono or use one analyzer
   * per channel.
   */
  analyze(): AnalysisResult
  /**
   * Analyzes buffered audio on a libuv worker thread and returns a promise for the scores.
   *
   * Uses the same analysis and silence padding as {@link Analyzer#analyze}.
   * {@link Analyzer#buffer} can continue collecting audio while analysis runs.
   *
   * Synchronous calls to `analyze`, `reset`, `updateBearerToken`, `terminateSession` and
   * `dispose` wait for the analyzer lock and may block while analysis is running.
   */
  analyzeAsync(): Promise<AnalysisResult>
  /** Clears buffered audio and internal state, keeping the configured audio settings. */
  reset(): void
  /**
   * Replaces the bearer token on the running analyzer.
   *
   * Use this to refresh a JWT without recreating the instance. Both the original license
   * key and the new token must be JWTs. If this call fails, the previous token remains active.
   *
   * A successful call validates the token's format and applies it immediately. Backend
   * acceptance is checked later. If the backend rejects the token, the SDK retries with
   * backoff; analysis may be rejected if no accepted token arrives in time.
   * Supply a valid token to recover the session.
   *
   * This method allocates memory and takes a mutex. Avoid calling it from audio callbacks.
   */
  updateBearerToken(token: string): void
  /**
   * Terminates the telemetry session associated with this analyzer.
   *
   * Once termination is handled, the analyzer can no longer analyze buffered audio.
   * The session also ends when the native analyzer is destroyed. This method may block;
   * avoid calling it from audio processing callbacks. If another session is still active,
   * termination can complete asynchronously.
   */
  terminateSession(): void
}

/**
 * A loaded ai-coustics model.
 *
 * The same model can be used to create multiple independent instances of a compatible
 * processor, VAD or analyzer. Each instance retains a reference to the model data,
 * so the Model handle can be disposed or garbage collected first.
 */
export declare class Model {
  /**
   * Loads a model from a `.aicmodel` file.
   *
   * The SDK memory-maps the file. Do not modify or delete it while the model or any
   * processor, VAD or analyzer created from it is still alive.
   *
   * Download models with {@link Model.download}. Available model IDs are listed at
   * https://artifacts.ai-coustics.io.
   *
   * @param path - Path to the model file.
   * @throws If the file cannot be loaded or its format is incompatible with this SDK.
   */
  static fromFile(path: string): Model
  /**
   * Releases this handle's reference to the native model without waiting for garbage collection.
   *
   * Instances created from this model remain usable. The file mapping is released when
   * its last reference is destroyed.
   *
   * After disposal, all methods except `dispose()` throw. Repeated disposal has no effect.
   */
  dispose(): void
  /**
   * Downloads a model from the ai-coustics CDN and returns a promise for its file path.
   *
   * Each call fetches the manifest to select the latest compatible model version.
   * An existing file is reused if its checksum matches; otherwise it is replaced.
   * The download runs on Node's libuv thread pool.
   *
   * @param modelId - Model ID listed at https://artifacts.ai-coustics.io.
   * @param downloadDir - Directory in which to store the model.
   * @returns A promise for the downloaded or cached model's path.
   */
  static download(modelId: string, downloadDir: string): Promise<string>
  /** Returns the model identifier, including its build and format version suffixes. */
  getId(): string
  /**
   * Returns the sample rate in Hz for which the model was trained.
   *
   * The SDK resamples audio at other supported rates internally. Enhancement is limited
   * to frequencies below half the model's sample rate.
   */
  getOptimalSampleRate(): number
  /**
   * Returns the optimal block size in samples for the given sample rate.
   *
   * Use this value to avoid additional buffering latency. The block size depends on the
   * sample rate because each model processes a fixed duration of audio.
   *
   * @param sampleRate - Audio sample rate in Hz.
   */
  getOptimalBlockSize(sampleRate: number): number
}

/**
 * Processes mono audio with an enhancement or bypass model.
 *
 * Call {@link Processor#initialize} before processing audio. Each processor maintains
 * its own state; create one instance per audio stream. Multiple processors can share
 * the same {@link Model}.
 *
 * Use {@link ProcessorAsync} to run processing on Node's libuv thread pool.
 */
export declare class Processor {
  /**
   * Creates a new speech enhancement processor.
   *
   * Construction is synchronous and throws if creation fails. Call
   * {@link Processor#initialize} before processing audio.
   *
   * @param model - Enhancement or bypass model. Other model types are rejected.
   * @param licenseKey - SDK license key from https://developers.ai-coustics.com.
   * @param otelConfig - Optional telemetry configuration. When omitted, telemetry follows
   *   the runtime environment.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native processor and releases its telemetry session.
   *
   * Use this for cleanup at a specific point instead of waiting for garbage collection.
   * After disposal, all methods except `dispose()` fail. Repeated disposal has no effect.
   */
  dispose(): void
  /**
   * Configures the processor for the given audio format.
   *
   * Call this method before processing audio. Use {@link Model#getOptimalSampleRate} and
   * {@link Model#getOptimalBlockSize} for the lowest delay.
   * This method allocates memory; avoid calling it from audio processing callbacks.
   *
   * @param sampleRate - Audio sample rate in Hz.
   * @param blockSize - Number of mono samples per block.
   * @param variableBlockSize - Allow blocks shorter than `blockSize`. Defaults to `false`.
   *   Variable block sizes can add buffering latency. Larger blocks are always rejected.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): void
  /**
   * Enhances a mono audio block in place.
   *
   * Call {@link Processor#initialize} first. The block must contain exactly `blockSize`
   * samples, or at most `blockSize` if `variableBlockSize` is enabled.
   * If the input uses a SharedArrayBuffer, prevent other workers from accessing it during
   * this call.
   */
  process(audio: Float32Array): void
  /**
   * Creates a handle for reading and writing this processor's parameters and state.
   *
   * Each call returns an independent handle onto the same processor.
   */
  getContext(): ProcessorContext
  /**
   * Terminates the telemetry session associated with this processor.
   *
   * Once termination is handled, the processor can no longer process audio.
   * The session also ends when the native object is destroyed. Use this method when
   * termination must be requested at a specific lifecycle event.
   *
   * This method may block. Avoid calling it from audio processing callbacks.
   * If another session is still active, termination can complete asynchronously.
   */
  terminateSession(): void
}

/**
 * Speech enhancement for use in async applications.
 *
 * Initialization, processing and context creation run on Node's libuv thread pool and
 * return promises. Construction and disposal are synchronous.
 * Use {@link Processor} when processing should run on the calling thread.
 *
 * ### Threading
 *
 * Use one instance per stream and await each operation before submitting the next.
 * Concurrent calls on one instance are not guaranteed to execute in submission order.
 * Use separate instances to process multiple streams concurrently.
 *
 * The libuv pool defaults to four threads and is shared with filesystem, DNS and crypto
 * work. Set `UV_THREADPOOL_SIZE` before starting Node to change its size.
 * `AIC_NUM_THREADS` does not apply to these bindings.
 */
export declare class ProcessorAsync {
  /**
   * Creates a new async speech enhancement processor.
   *
   * Construction is synchronous and throws if creation fails. Call
   * {@link ProcessorAsync#initialize} or {@link ProcessorAsync#withConfig} before processing audio.
   *
   * @param model - Enhancement or bypass model. Other model types are rejected.
   * @param licenseKey - SDK license key from https://developers.ai-coustics.com.
   * @param otelConfig - Optional telemetry configuration. When omitted, telemetry follows
   *   the runtime environment.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native processor and releases its telemetry session.
   *
   * Use this for cleanup at a specific point instead of waiting for garbage collection.
   * After disposal, all methods except `dispose()` fail. Repeated disposal has no effect.
   *
   * This call blocks the calling thread while a worker holds the instance lock.
   * Queued work that acquires the lock after disposal rejects its promise.
   */
  dispose(): void
  /**
   * Initializes the processor and returns a promise for a handle to the initialized instance.
   *
   * Uses the same configuration as {@link ProcessorAsync#initialize}. The returned handle and
   * this object share the same native instance; disposing either invalidates both.
   *
   * ```js
   * const processor = await new ProcessorAsync(model, licenseKey).withConfig(sampleRate, blockSize)
   * ```
   */
  withConfig(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<ProcessorAsync>
  /**
   * Configures the processor for the given audio format.
   *
   * Await this method before processing audio. Use {@link Model#getOptimalSampleRate} and
   * {@link Model#getOptimalBlockSize} for the lowest delay.
   * Initialization allocates memory and runs on a libuv worker thread.
   *
   * @param sampleRate - Audio sample rate in Hz.
   * @param blockSize - Number of mono samples per block.
   * @param variableBlockSize - Allow blocks shorter than `blockSize`. Defaults to `false`.
   *   Variable block sizes can add buffering latency. Larger blocks are always rejected.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<void>
  /**
   * Enhances a mono audio block and returns a promise for the enhanced samples.
   *
   * The input is copied before work is queued and remains unmodified. The promise
   * resolves to a new `Float32Array` containing the enhanced samples.
   *
   * The instance must be initialized first. The block must contain exactly `blockSize`
   * samples, or at most `blockSize` if `variableBlockSize` is enabled.
   * Await each call before submitting the next block.
   *
   * ```js
   * const enhanced = await processor.process(block)
   * ```
   */
  process(audio: Float32Array): Promise<Float32Array<ArrayBuffer>>
  /**
   * Returns a promise for a {@link ProcessorContext} to control this processor.
   *
   * Context creation runs on a worker thread because it may wait for processing to
   * release the instance lock. The returned context's methods are synchronous and can
   * be called while audio is being processed.
   */
  getContext(): Promise<ProcessorContext>
  /**
   * Terminates the telemetry session associated with this processor.
   *
   * Once termination is handled, the processor can no longer process audio.
   * The session also ends when the native object is destroyed. Use this method when
   * termination must be requested at a specific lifecycle event.
   *
   * Termination runs on a libuv worker thread because it may block.
   * If another session is still active, termination can complete asynchronously.
   */
  terminateSession(): Promise<void>
}

/**
 * Control handle for a {@link Processor}.
 *
 * Every method may be called while audio is being processed. Handle and processor have
 * independent lifetimes: releasing the handle does not destroy the processor, and the
 * handle stays valid after its processor is disposed or garbage-collected, though its
 * calls then no longer reach a live processor.
 */
export declare class ProcessorContext {
  /** Sets an enhancement parameter. Throws if the value is out of range. */
  setParameter(parameter: ProcessorParameter, value: number): void
  /** Reads the current value of a parameter. */
  getParameter(parameter: ProcessorParameter): number
  /**
   * Total delay the processor applies to the audio, in samples at the initialized rate.
   *
   * Covers algorithmic delay plus any buffering from a non-optimal block size. Before
   * initialization it reports the base delay at the model's optimal settings.
   */
  getAudioDelay(): number
  /**
   * Clears internal state and buffers while preserving the configured audio settings.
   *
   * Call this when the stream is interrupted or when seeking to prevent previous audio
   * from affecting the output.
   */
  reset(): void
  /**
   * Replaces the bearer token on the running processor.
   *
   * Use this to refresh a JWT without recreating the instance. Both the original license
   * key and the new token must be JWTs. If this call fails, the previous token remains active.
   *
   * A successful call validates the token's format and applies it immediately. Backend
   * acceptance is checked later. If the backend rejects the token, the SDK retries with
   * backoff; processing is eventually disabled if no accepted token arrives in time.
   * Supply a valid token to recover the session.
   *
   * This method allocates memory and takes a mutex. Avoid calling it from audio callbacks.
   */
  updateBearerToken(token: string): void
}

/**
 * Detects speech using a dedicated VAD model.
 *
 * Call {@link Vad#initialize}, then pass mono audio to {@link Vad#process}.
 * Processing leaves the audio unmodified and updates the prediction, which can be read
 * through a {@link VadContext}.
 *
 * When using enhancement and detection together, pass the original input to the VAD
 * before calling {@link Processor#process}. Enhanced audio changes the signal seen by
 * the VAD and adds the processor's audio delay to the prediction delay.
 */
export declare class Vad {
  /**
   * Creates a new voice activity detector.
   *
   * Construction is synchronous and throws if creation fails. Call
   * {@link Vad#initialize} before processing audio.
   *
   * @param model - Dedicated VAD model. Other model types are rejected.
   * @param licenseKey - SDK license key from https://developers.ai-coustics.com.
   * @param otelConfig - Optional telemetry configuration. When omitted, telemetry follows
   *   the runtime environment.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native VAD and releases its telemetry session.
   *
   * Use this for cleanup at a specific point instead of waiting for garbage collection.
   * After disposal, all methods except `dispose()` fail. Repeated disposal has no effect.
   */
  dispose(): void
  /**
   * Configures the VAD for the given audio format.
   *
   * Call this method before processing audio. Use {@link Model#getOptimalSampleRate} and
   * {@link Model#getOptimalBlockSize} for the most frequent prediction updates.
   * This method allocates memory; avoid calling it from audio processing callbacks.
   *
   * @param sampleRate - Audio sample rate in Hz.
   * @param blockSize - Number of mono samples per block.
   * @param variableBlockSize - Allow blocks shorter than `blockSize`. Defaults to `false`.
   *   Variable block sizes can add buffering latency. Larger blocks are always rejected.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): void
  /**
   * Processes a mono audio block and updates the VAD prediction without modifying the input.
   *
   * Call {@link Vad#initialize} first. The block must contain exactly `blockSize` samples,
   * or at most `blockSize` if `variableBlockSize` is enabled.
   */
  process(audio: Float32Array): void
  /**
   * Creates a handle for reading predictions and controlling this VAD.
   *
   * Each call returns an independent handle onto the same VAD.
   */
  getContext(): VadContext
  /**
   * Terminates the telemetry session associated with this VAD.
   *
   * Once termination is handled, the VAD can no longer process audio.
   * The session also ends when the native object is destroyed. Use this method when
   * termination must be requested at a specific lifecycle event.
   *
   * This method may block. Avoid calling it from audio processing callbacks.
   * If another session is still active, termination can complete asynchronously.
   */
  terminateSession(): void
}

/**
 * Voice activity detection for use in async applications.
 *
 * Initialization, processing and context creation run on Node's libuv thread pool and
 * return promises. Construction and disposal are synchronous.
 * Read predictions through a {@link VadContext}. Feed the VAD original input audio before enhancement.
 *
 * ### Threading
 *
 * Use one instance per stream and await each operation before submitting the next.
 * Concurrent calls on one instance are not guaranteed to execute in submission order.
 * Use separate instances to process multiple streams concurrently.
 *
 * The libuv pool defaults to four threads and is shared with filesystem, DNS and crypto
 * work. Set `UV_THREADPOOL_SIZE` before starting Node to change its size.
 * `AIC_NUM_THREADS` does not apply to these bindings.
 */
export declare class VadAsync {
  /**
   * Creates a new async voice activity detector.
   *
   * Construction is synchronous and throws if creation fails. Call
   * {@link VadAsync#initialize} or {@link VadAsync#withConfig} before processing audio.
   *
   * @param model - Dedicated VAD model. Other model types are rejected.
   * @param licenseKey - SDK license key from https://developers.ai-coustics.com.
   * @param otelConfig - Optional telemetry configuration. When omitted, telemetry follows
   *   the runtime environment.
   */
  constructor(model: Model, licenseKey: string, otelConfig?: OtelConfig | undefined | null)
  /**
   * Destroys the native VAD and releases its telemetry session.
   *
   * Use this for cleanup at a specific point instead of waiting for garbage collection.
   * After disposal, all methods except `dispose()` fail. Repeated disposal has no effect.
   *
   * This call blocks the calling thread while a worker holds the instance lock.
   * Queued work that acquires the lock after disposal rejects its promise.
   */
  dispose(): void
  /**
   * Initializes the VAD and returns a promise for a handle to the initialized instance.
   *
   * Uses the same configuration as {@link VadAsync#initialize}. The returned handle and
   * this object share the same native instance; disposing either invalidates both.
   *
   * ```js
   * const vad = await new VadAsync(model, licenseKey).withConfig(sampleRate, blockSize)
   * ```
   */
  withConfig(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<VadAsync>
  /**
   * Configures the VAD for the given audio format.
   *
   * Await this method before processing audio. Use {@link Model#getOptimalSampleRate} and
   * {@link Model#getOptimalBlockSize} for the most frequent prediction updates.
   * Initialization allocates memory and runs on a libuv worker thread.
   *
   * @param sampleRate - Audio sample rate in Hz.
   * @param blockSize - Number of mono samples per block.
   * @param variableBlockSize - Allow blocks shorter than `blockSize`. Defaults to `false`.
   *   Variable block sizes can add buffering latency. Larger blocks are always rejected.
   */
  initialize(sampleRate: number, blockSize: number, variableBlockSize?: boolean | undefined | null): Promise<void>
  /**
   * Processes a mono audio block and updates the VAD prediction.
   *
   * The input is copied before work is queued and remains unmodified. The promise
   * resolves to a new `Float32Array` containing the original samples.
   *
   * The instance must be initialized first. The block must contain exactly `blockSize`
   * samples, or at most `blockSize` if `variableBlockSize` is enabled.
   * Await each call before submitting the next block.
   *
   * ```js
   * const audio = await vad.process(block)
   * ```
   */
  process(audio: Float32Array): Promise<Float32Array<ArrayBuffer>>
  /**
   * Returns a promise for a {@link VadContext} to control this VAD and read predictions.
   *
   * Context creation runs on a worker thread because it may wait for processing to
   * release the instance lock. The returned context's methods are synchronous and can
   * be called while audio is being processed.
   */
  getContext(): Promise<VadContext>
  /**
   * Terminates the telemetry session associated with this VAD.
   *
   * Once termination is handled, the VAD can no longer process audio.
   * The session also ends when the native object is destroyed. Use this method when
   * termination must be requested at a specific lifecycle event.
   *
   * Termination runs on a libuv worker thread because it may block.
   * If another session is still active, termination can complete asynchronously.
   */
  terminateSession(): Promise<void>
}

/**
 * Control handle for a {@link Vad}.
 *
 * Every method may be called while audio is being processed. If the backing VAD is
 * released the prediction stops updating, but this handle stays valid.
 */
export declare class VadContext {
  /** Sets a VAD parameter. Throws if the value is out of range. */
  setParameter(parameter: VadParameter, value: number): void
  /** Reads the current value of a VAD parameter. */
  getParameter(parameter: VadParameter): number
  /**
   * Whether speech is currently detected.
   *
   * The decision lags its input by {@link VadContext#getPredictionDelay} samples, and
   * stops updating if the backing VAD stops being processed.
   */
  isSpeechDetected(): boolean
  /**
   * Returns the model's speech probability in the range 0.0 to 1.0.
   *
   * This value excludes speech hold, sensitivity thresholding and minimum speech duration.
   * Use it to implement custom detection logic. The prediction delay reported by
   * {@link VadContext#getPredictionDelay} also applies to this value.
   */
  getRawVadProbability(): number
  /**
   * Returns the prediction delay in samples at the configured sample rate.
   *
   * Includes input buffering, STFT and model processing. Non-optimal or variable block
   * sizes can add buffering latency. Convert to milliseconds with
   * `delaySamples * 1000 / sampleRate`.
   *
   * Use this delay to align speech decisions with the input audio. It is independent of
   * a processor's audio delay; VAD processing does not delay or modify the audio.
   */
  getPredictionDelay(): number
  /**
   * Clears internal state and buffers, including the published speech decision and probability.
   *
   * Call this when the stream is interrupted or when seeking to prevent predictions
   * from using previous audio. The VAD remains initialized with its configured settings.
   */
  reset(): void
  /**
   * Replaces the bearer token on the running VAD.
   *
   * Use this to refresh a JWT without recreating the instance. Both the original license
   * key and the new token must be JWTs. If this call fails, the previous token remains active.
   *
   * A successful call validates the token's format and applies it immediately. Backend
   * acceptance is checked later. If the backend rejects the token, the SDK retries with
   * backoff; processing is eventually disabled if no accepted token arrives in time.
   * Supply a valid token to recover the session.
   *
   * This method allocates memory and takes a mutex. Avoid calling it from audio callbacks.
   */
  updateBearerToken(token: string): void
}

/**
 * Overrides the telemetry wrapper id. Internal only, for ai-coustics wrappers embedding
 * this package (e.g. the LiveKit plugin): call before constructing any `Processor`, `Vad`
 * or `Analyzer`, whose constructors otherwise claim the id for this SDK. The id can only
 * be set once per process; later writes are silently discarded.
 */
export declare function _setSdkId(id: number): void

/**
 * Results of analyzing an audio signal with {@link Analyzer}.
 *
 * Scores range from 0.0 to 1.0. For every field except `speakerLoudness`, lower values
 * indicate less problematic audio.
 */
export interface AnalysisResult {
  /**
   * Predicts the likelihood of failure in downstream models, including speech-to-text,
   * voice activity detection, turn-taking and speech-to-speech models.
   */
  riskScore: number
  /** Measure of speaker distance and reverberation. */
  speakerReverb: number
  /** Measure of speaker loudness. */
  speakerLoudness: number
  /** Measure of interfering speech from sources other than the main speaker. */
  interferingSpeech: number
  /** Measure of ambient or environmental noise. */
  noise: number
  /** Artifacts from lossy speech codecs, e.g. a low bitrate or narrowband codec. */
  codecDegradation: number
  /**
   * Dropouts and discontinuities, e.g. from packet loss, frame erasure, jitter or CPU
   * overload.
   */
  packetLoss: number
}

/** Returns the model file format version supported by this SDK. */
export declare function getCompatibleModelVersion(): number

/**
 * Returns the version of the underlying native SDK.
 *
 * This may differ from the Node.js package version.
 */
export declare function getVersion(): string

/**
 * OpenTelemetry configuration for a processor or VAD instance.
 *
 * Overrides the SDK's environment-based telemetry settings, such as
 * `AIC_SDK_OTEL_ENABLE`, for the instance receiving this configuration.
 */
export interface OtelConfig {
  /** Whether to export telemetry. */
  enable: boolean
  /** Session id to report. A random one is generated when omitted. */
  sessionId?: string
  /** Metric export interval in milliseconds. Omit or pass 0 for the SDK default of 60000. */
  exportIntervalMs?: number
}

/** Configurable speech enhancement parameters. Values can be changed during processing. */
export declare const enum ProcessorParameter {
  /**
   * Bypasses enhancement while preserving the processing delay.
   *
   * This allows enhancement to be enabled or disabled without clicks or timing changes.
   *
   * Range: 0.0 to 1.0. At 0.0 enhancement is active; at 1.0 audio passes through with
   * latency compensation. Default: 0.0.
   */
  Bypass = 0,
  /**
   * Controls enhancement strength.
   *
   * Quail models apply stronger noise suppression at higher values, including suppression
   * of competing speech for Voice Focus models. Rook models adjust the mix of original
   * and enhanced audio.
   *
   * Range: 0.0 to 1.0.
   */
  EnhancementLevel = 1
}

/** Configurable voice activity detection parameters. Values can be changed during processing. */
export declare const enum VadParameter {
  /**
   * Controls how long the VAD continues reporting speech after speech stops.
   *
   * Speech is reported if at least half the blocks processed in the last
   * `speechHoldDuration * 2` seconds contained speech. Additional speech during this
   * period extends the detection period.
   *
   * The duration is rounded to the nearest model window length, so the value read back
   * may differ from the value set.
   *
   * Range: 0.0 to 300 times the model window length, in seconds. Default: model-specific.
   */
  SpeechHoldDuration = 0,
  /**
   * Sets the probability threshold for detecting speech in an audio block.
   *
   * A model probability above this threshold counts as speech.
   *
   * Range: 0.0 to 1.0. Default: model-specific.
   */
  Sensitivity = 1,
  /**
   * Controls how long speech must be present before the VAD reports speech.
   *
   * The duration is rounded to the nearest model window length, so the value read back
   * may differ from the value set.
   *
   * Range: 0.0 to 1.0 seconds. Default: model-specific.
   */
  MinimumSpeechDuration = 2
}
